version: '3'
services:
  
  # database
  db:    
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db 
      - mongo-config:/data/configdb 
    ports:
      - 27017:27017  
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: ad-caspar
    networks:
      - mongo-net
  
  # mongo-express
  mongo-express:    
    image: mongo-express:0.54.0
    container_name: mongo-express
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8087:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: tribes
    networks:
      - mongo-net
  
networks:
  mongo-net:  
volumes:
  mongo-data:
  mongo-config: